#!/usr/bin/env -S node --no-warnings
/**
 * map-render — read the codegraph SQLite index and emit visualisations.
 *
 * Outputs (under .codegraph/):
 *   graph.md    — Mermaid module-level graph of packages/core/src/, tier-grouped.
 *                  Render in any markdown viewer that supports Mermaid
 *                  (GitHub, VS Code, Obsidian, etc.).
 *   graph.html  — Interactive full-symbol graph (Cytoscape, CDN-loaded).
 *                  Open in a browser. ~700 nodes, ~1.8k edges.
 *   graph.json  — Raw {nodes, edges} for piping into other tools.
 *
 * Uses node:sqlite (Node 22+). No npm deps.
 */

import { DatabaseSync } from 'node:sqlite'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'

const repoRoot = resolve(dirname(new URL(import.meta.url).pathname), '../../..')
const dbPath = resolve(repoRoot, '.codegraph/codegraph.db')
const outDir = resolve(repoRoot, '.codegraph')

const db = new DatabaseSync(dbPath, { readOnly: true })

// ── Data extraction ──────────────────────────────────────────────────────────

interface Node {
  id: string
  kind: string
  name: string
  file_path: string
  start_line: number
  is_exported: number
}

interface Edge {
  source: string
  target: string
  kind: string
}

const nodes: Node[] = db
  .prepare('SELECT id, kind, name, file_path, start_line, is_exported FROM nodes')
  .all() as unknown as Node[]

const edges: Edge[] = db.prepare('SELECT source, target, kind FROM edges').all() as unknown as Edge[]

db.close()

// Index by id for fast lookup
const nodeById = new Map(nodes.map((n) => [n.id, n]))

// ── Mermaid module graph ─────────────────────────────────────────────────────
//
// File-level import dependencies within packages/core/src/, grouped into tiers
// matching the canonical doc. This is the architecture tour.

const TIER_MAP: Record<string, string> = {
  // Tier 0 — foundations
  'world.ts': 'Tier0',
  'entity.ts': 'Tier0',
  'clock.ts': 'Tier0',
  'trace.ts': 'Tier0',
  'did.ts': 'Tier0',
  'schema/index.ts': 'Tier0',
  'schema/soa.ts': 'Tier0',
  'schema/kinds.ts': 'Tier0',
  // Tier 1 — ECS primitives
  'component.ts': 'Tier1',
  'relation.ts': 'Tier1',
  'observer.ts': 'Tier1',
  // Tier 2 — identity + query
  'identity.ts': 'Tier2',
  'query.ts': 'Tier2',
  // Tier 3 — systems + pipeline + prefabs + snapshot + transport
  'system.ts': 'Tier3',
  'mutation.ts': 'Tier3',
  'prefab.ts': 'Tier3',
  'snapshot.ts': 'Tier3',
  'transport.ts': 'Tier3',
  // Tier 4 — peers + authority + ZCAP + governance
  'peer.ts': 'Tier4',
  'authority.ts': 'Tier4',
  'zcap.ts': 'Tier4',
  'governance.ts': 'Tier4'
}

const TIER_LABELS: Record<string, string> = {
  Tier0: 'Tier 0 — Foundations',
  Tier1: 'Tier 1 — ECS primitives',
  Tier2: 'Tier 2 — Identity & Query',
  Tier3: 'Tier 3 — Systems · Pipeline · Prefabs · Snapshot · Transport',
  Tier4: 'Tier 4 — Peers · Authority · ZCAP · Governance'
}

const CORE_PREFIX = 'packages/core/src/'

const isCoreFile = (path: string): boolean =>
  path.startsWith(CORE_PREFIX) && !path.endsWith('.test.ts') && !path.includes('/test-utils/')

const fileRel = (path: string): string => path.slice(CORE_PREFIX.length)

const sanitiseId = (s: string): string => s.replace(/[^a-zA-Z0-9]/g, '_')

// Build file → file dependency edges from `calls` + `references` between symbols
// in different files. (The native `imports` edge targets the import statement
// node itself, with the unresolved specifier as `name` — useful for module
// boundary lists but not for resolved file→file edges.)
const fileImports = new Map<string, Set<string>>()
for (const edge of edges) {
  if (edge.kind !== 'calls' && edge.kind !== 'references') continue
  const src = nodeById.get(edge.source)
  const tgt = nodeById.get(edge.target)
  if (!src || !tgt) continue
  if (!isCoreFile(src.file_path) || !isCoreFile(tgt.file_path)) continue
  const srcRel = fileRel(src.file_path)
  const tgtRel = fileRel(tgt.file_path)
  if (srcRel === tgtRel) continue
  if (!fileImports.has(srcRel)) fileImports.set(srcRel, new Set())
  fileImports.get(srcRel)!.add(tgtRel)
}

// Group files by tier
const tierFiles = new Map<string, Set<string>>()
for (const path of new Set([...fileImports.keys(), ...[...fileImports.values()].flatMap((s) => [...s])])) {
  const tier = TIER_MAP[path] ?? 'Misc'
  if (!tierFiles.has(tier)) tierFiles.set(tier, new Set())
  tierFiles.get(tier)!.add(path)
}

const mermaidLines: string[] = []
mermaidLines.push('# Connection Engine — Module Graph')
mermaidLines.push('')
mermaidLines.push(
  'Auto-generated by `pnpm --filter @connectionengine/core map:render` from the codegraph index. Cross-file `calls` + `references` edges within `packages/core/src/`, grouped by tier per the canonical exploration doc.'
)
mermaidLines.push('')
mermaidLines.push('```mermaid')
mermaidLines.push('graph LR')
mermaidLines.push('')

const tierOrder = ['Tier0', 'Tier1', 'Tier2', 'Tier3', 'Tier4', 'Misc']
for (const tier of tierOrder) {
  const files = tierFiles.get(tier)
  if (!files || files.size === 0) continue
  const label = TIER_LABELS[tier] ?? tier
  mermaidLines.push(`  subgraph ${tier}["${label}"]`)
  for (const path of [...files].sort()) {
    mermaidLines.push(`    ${sanitiseId(path)}["${path}"]`)
  }
  mermaidLines.push('  end')
  mermaidLines.push('')
}

// Edges last so subgraph placement is honoured
for (const [src, targets] of [...fileImports.entries()].sort()) {
  for (const tgt of [...targets].sort()) {
    mermaidLines.push(`  ${sanitiseId(src)} --> ${sanitiseId(tgt)}`)
  }
}

// Soft style per tier
mermaidLines.push('')
mermaidLines.push('  classDef tier0 fill:#1a2332,stroke:#4a90e2,color:#e8f0ff')
mermaidLines.push('  classDef tier1 fill:#1a3322,stroke:#4ae29e,color:#e8ffea')
mermaidLines.push('  classDef tier2 fill:#332a1a,stroke:#e2c14a,color:#fff5e0')
mermaidLines.push('  classDef tier3 fill:#331a2a,stroke:#e24aab,color:#ffe8f5')
mermaidLines.push('  classDef tier4 fill:#2a1a33,stroke:#a04ae2,color:#f5e8ff')
for (const [tier, files] of tierFiles) {
  const cls = tier.toLowerCase()
  if (!['tier0', 'tier1', 'tier2', 'tier3', 'tier4'].includes(cls)) continue
  const ids = [...files].map(sanitiseId).join(',')
  mermaidLines.push(`  class ${ids} ${cls}`)
}

mermaidLines.push('```')
mermaidLines.push('')
mermaidLines.push('## Stats')
mermaidLines.push('')
mermaidLines.push(`- ${fileImports.size} files emitting cross-file dependencies`)
mermaidLines.push(
  `- ${[...fileImports.values()].reduce((sum, s) => sum + s.size, 0)} cross-file edges (calls + references) among core source files`
)
mermaidLines.push(`- ${nodes.length} total symbols (functions, interfaces, classes, …) across the full repo index`)
mermaidLines.push(`- ${edges.length} total edges in the codegraph index`)
mermaidLines.push('')
mermaidLines.push('See `graph.html` for the interactive full-symbol view.')

// ── Cytoscape HTML ──────────────────────────────────────────────────────────
//
// Full graph (~700 nodes, ~1.8k edges). Self-contained: Cytoscape from CDN,
// graph data inlined as JSON. Filter chips by kind, search-as-you-type.

interface ExportNode {
  data: {
    id: string
    label: string
    kind: string
    file: string
    line: number
    exported: boolean
  }
}
interface ExportEdge {
  data: { id: string; source: string; target: string; kind: string }
}

const exportNodes: ExportNode[] = nodes
  .filter((n) => n.kind !== 'import') // imports are noise at symbol level
  .map((n) => ({
    data: {
      id: n.id,
      label: n.name,
      kind: n.kind,
      file: n.file_path,
      line: n.start_line,
      exported: n.is_exported === 1
    }
  }))

const nodeIds = new Set(exportNodes.map((n) => n.data.id))
const exportEdges: ExportEdge[] = edges
  .filter((e) => e.kind !== 'contains') // file→symbol containment is implicit via the `file` field
  .filter((e) => nodeIds.has(e.source) && nodeIds.has(e.target))
  .map((e, i) => ({
    data: { id: `e${i}`, source: e.source, target: e.target, kind: e.kind }
  }))

const graphJson = JSON.stringify({ nodes: exportNodes, edges: exportEdges })

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Connection Engine — Code Graph</title>
<script src="https://unpkg.com/cytoscape@3.30.4/dist/cytoscape.min.js"></script>
<script src="https://unpkg.com/cytoscape-cose-bilkent@4.1.0/cytoscape-cose-bilkent.js"></script>
<style>
  html, body { margin: 0; padding: 0; height: 100%; background: #0e1116; color: #e6e6e6; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }
  #cy { position: absolute; top: 56px; left: 0; right: 320px; bottom: 0; background: #0e1116; }
  #panel { position: absolute; top: 56px; right: 0; bottom: 0; width: 320px; background: #161a22; border-left: 1px solid #2a2f3a; padding: 16px; overflow-y: auto; box-sizing: border-box; }
  #toolbar { position: absolute; top: 0; left: 0; right: 0; height: 56px; background: #161a22; border-bottom: 1px solid #2a2f3a; display: flex; align-items: center; padding: 0 16px; gap: 12px; }
  #toolbar h1 { margin: 0; font-size: 14px; font-weight: 600; color: #e6e6e6; }
  #toolbar .stats { color: #8b95a5; font-size: 12px; }
  #search { flex: 1; max-width: 320px; background: #0e1116; border: 1px solid #2a2f3a; color: #e6e6e6; padding: 6px 10px; border-radius: 4px; font-size: 13px; }
  .chip { display: inline-flex; align-items: center; gap: 6px; padding: 4px 10px; border-radius: 12px; font-size: 11px; cursor: pointer; user-select: none; background: #1f2530; color: #c9d1d9; border: 1px solid #2a2f3a; }
  .chip.on { background: #2d4a8a; border-color: #4a90e2; color: #fff; }
  .chip .swatch { width: 8px; height: 8px; border-radius: 50%; }
  #legend { display: flex; flex-wrap: wrap; gap: 6px; padding-bottom: 12px; border-bottom: 1px solid #2a2f3a; margin-bottom: 12px; }
  .info { font-size: 12px; line-height: 1.5; }
  .info h2 { font-size: 13px; margin: 0 0 4px 0; color: #fff; }
  .info .kind { color: #8b95a5; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
  .info .file { color: #4a90e2; font-family: monospace; font-size: 11px; margin-top: 4px; word-break: break-all; }
  .info .list { margin-top: 8px; }
  .info .list .label { color: #8b95a5; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; margin-top: 8px; margin-bottom: 4px; }
  .info .list .item { padding: 2px 0; font-family: monospace; font-size: 11px; color: #c9d1d9; cursor: pointer; }
  .info .list .item:hover { color: #4a90e2; }
  .empty { color: #8b95a5; font-size: 12px; font-style: italic; }
</style>
</head>
<body>
<div id="toolbar">
  <h1>Connection Engine</h1>
  <span class="stats">${exportNodes.length} symbols · ${exportEdges.length} edges</span>
  <input id="search" placeholder="Search by name…">
</div>
<div id="cy"></div>
<div id="panel">
  <div id="legend"></div>
  <div id="info" class="empty">Click a node to inspect.</div>
</div>
<script>
const GRAPH = ${graphJson};

const KIND_COLOURS = {
  function:   '#4ae29e',
  method:     '#4ae29e',
  class:      '#e2c14a',
  interface:  '#4a90e2',
  type_alias: '#8b95a5',
  constant:   '#e24aab',
  file:       '#666',
  route:      '#a04ae2'
};
const EDGE_COLOURS = {
  calls:      '#4ae29e',
  references: '#4a90e2',
  imports:    '#8b95a5'
};

const cy = cytoscape({
  container: document.getElementById('cy'),
  elements: { nodes: GRAPH.nodes, edges: GRAPH.edges },
  style: [
    { selector: 'node', style: {
      'background-color': ele => KIND_COLOURS[ele.data('kind')] || '#666',
      'label': 'data(label)',
      'color': '#e6e6e6',
      'font-size': 9,
      'text-valign': 'bottom',
      'text-margin-y': 4,
      'width': ele => ele.data('exported') ? 16 : 10,
      'height': ele => ele.data('exported') ? 16 : 10,
      'border-width': ele => ele.data('exported') ? 1.5 : 0,
      'border-color': '#fff',
      'text-outline-color': '#0e1116',
      'text-outline-width': 2
    }},
    { selector: 'edge', style: {
      'curve-style': 'bezier',
      'line-color': ele => EDGE_COLOURS[ele.data('kind')] || '#444',
      'target-arrow-color': ele => EDGE_COLOURS[ele.data('kind')] || '#444',
      'target-arrow-shape': 'triangle',
      'width': 1,
      'opacity': 0.45,
      'arrow-scale': 0.8
    }},
    { selector: '.highlight', style: { 'opacity': 1, 'width': 2 } },
    { selector: 'node.highlight', style: { 'border-width': 2, 'border-color': '#fff' } },
    { selector: '.faded', style: { 'opacity': 0.08 } }
  ],
  layout: { name: 'cose-bilkent', animate: false, idealEdgeLength: 80, nodeRepulsion: 4500, randomize: false, fit: true, padding: 30 },
  wheelSensitivity: 0.2
});

// Legend + kind filters
const allKinds = [...new Set(GRAPH.nodes.map(n => n.data.kind))].sort();
const visibleKinds = new Set(allKinds);
const legendEl = document.getElementById('legend');
for (const k of allKinds) {
  const chip = document.createElement('span');
  chip.className = 'chip on';
  chip.innerHTML = '<span class="swatch" style="background:' + (KIND_COLOURS[k]||'#666') + '"></span>' + k;
  chip.addEventListener('click', () => {
    if (visibleKinds.has(k)) { visibleKinds.delete(k); chip.classList.remove('on'); }
    else { visibleKinds.add(k); chip.classList.add('on'); }
    cy.nodes().forEach(n => n.style('display', visibleKinds.has(n.data('kind')) ? 'element' : 'none'));
  });
  legendEl.appendChild(chip);
}

// Search
document.getElementById('search').addEventListener('input', (ev) => {
  const q = ev.target.value.toLowerCase().trim();
  if (!q) { cy.elements().removeClass('faded'); return; }
  const matched = cy.nodes().filter(n => n.data('label').toLowerCase().includes(q));
  cy.elements().addClass('faded');
  matched.removeClass('faded').forEach(n => n.connectedEdges().removeClass('faded'));
});

// Click to inspect
cy.on('tap', 'node', (ev) => {
  const n = ev.target;
  cy.elements().removeClass('highlight faded');
  cy.elements().addClass('faded');
  n.removeClass('faded').addClass('highlight');
  n.neighborhood().removeClass('faded').addClass('highlight');

  const incoming = n.incomers('edge');
  const outgoing = n.outgoers('edge');
  const renderList = (label, edges, dir) => edges.length === 0 ? '' :
    '<div class="label">' + label + ' (' + edges.length + ')</div>' +
    edges.map(e => {
      const other = dir === 'in' ? e.source() : e.target();
      return '<div class="item" data-id="' + other.id() + '">[' + e.data('kind') + '] ' + other.data('label') + '</div>';
    }).join('');

  document.getElementById('info').className = 'info';
  document.getElementById('info').innerHTML =
    '<div class="kind">' + n.data('kind') + (n.data('exported') ? ' · exported' : '') + '</div>' +
    '<h2>' + n.data('label') + '</h2>' +
    '<div class="file">' + n.data('file') + ':' + n.data('line') + '</div>' +
    '<div class="list">' + renderList('Incoming', incoming, 'in') + renderList('Outgoing', outgoing, 'out') + '</div>';

  document.querySelectorAll('.info .item').forEach(el => {
    el.addEventListener('click', () => {
      const target = cy.getElementById(el.dataset.id);
      if (target) {
        cy.center(target);
        target.trigger('tap');
      }
    });
  });
});
cy.on('tap', (ev) => { if (ev.target === cy) { cy.elements().removeClass('faded highlight'); document.getElementById('info').className = 'empty'; document.getElementById('info').textContent = 'Click a node to inspect.'; } });
</script>
</body>
</html>
`

// ── Write outputs ────────────────────────────────────────────────────────────

mkdirSync(outDir, { recursive: true })
writeFileSync(resolve(outDir, 'graph.md'), mermaidLines.join('\n'))
writeFileSync(resolve(outDir, 'graph.html'), html)
writeFileSync(
  resolve(outDir, 'graph.json'),
  JSON.stringify(
    {
      meta: {
        generated: new Date().toISOString(),
        totalNodes: nodes.length,
        totalEdges: edges.length,
        exportedNodes: exportNodes.length,
        exportedEdges: exportEdges.length
      },
      nodes: exportNodes,
      edges: exportEdges
    },
    null,
    2
  )
)

const rel = (p: string) => relative(process.cwd(), p)
console.log(`✓ Wrote ${rel(resolve(outDir, 'graph.md'))}   (Mermaid module graph, tier-grouped)`)
console.log(`✓ Wrote ${rel(resolve(outDir, 'graph.html'))} (Interactive ${exportNodes.length}-node Cytoscape view)`)
console.log(`✓ Wrote ${rel(resolve(outDir, 'graph.json'))} (Raw graph data)`)
